# permissions for end users to edit xcronjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xcronjob-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - xcronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - xcronjobs/status
  verbs:
  - get
